/**
 * The committed OBS template, guarded.
 *
 * `obs-template/` is generated by `scripts/derive-obs-scene-template.mts`, which drives a real OBS
 * and harvests what it writes. That is the right way to get the format right, and it is also how
 * one developer's hardware ends up in a file that ships to a church. The first derivation produced
 * eight such lines — `C:\Users\user\Videos` as the recording path, `nvenc` as the encoder on a
 * machine with an NVIDIA GPU, a Korean monitoring-device name, a machine-local browser CookieId.
 *
 * On a church PC each of those fails differently and none of them fails loudly:
 *   - a recording path that does not exist breaks Standing Rule 3's always-on recording, and the
 *     operator finds out after the service, when the recording is not there;
 *   - an encoder the machine lacks makes OBS refuse to start the output at all.
 *
 * The generator sanitises via an allowlist. These tests are the second half of that: they fail if a
 * re-derivation reintroduces machine state, and they fail if the browser source — the entire reason
 * the template exists — is wired wrong.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

const REPO_ROOT = join(import.meta.dirname, '..', '..', '..')
const TEMPLATE = join(REPO_ROOT, 'obs-template', 'config', 'obs-studio')
const SCENE_FILE = join(TEMPLATE, 'basic', 'scenes', 'Verger.json')
const PROFILE_FILE = join(TEMPLATE, 'basic', 'profiles', 'Verger', 'basic.ini')
const USER_INI = join(TEMPLATE, 'user.ini')

interface ObsSource {
  readonly id: string
  readonly name: string
  readonly settings?: Record<string, unknown>
}
interface ObsCollection {
  readonly name: string
  readonly sources: readonly ObsSource[]
  readonly scene_order: ReadonlyArray<{ name: string }>
  readonly current_program_scene: string
}

const collection = JSON.parse(readFileSync(SCENE_FILE, 'utf8')) as ObsCollection
const profileIni = readFileSync(PROFILE_FILE, 'utf8')
const userIni = readFileSync(USER_INI, 'utf8')

function browserSource(): ObsSource {
  const found = collection.sources.find((s) => s.id === 'browser_source')
  if (found === undefined) throw new Error('the template has no browser source at all')
  return found
}

describe('the profile carries no trace of the machine that generated it', () => {
  it.each([
    ['a Windows drive path', /[A-Za-z]:\\/],
    ['a hardware encoder', /nvenc|amf|qsv/i],
    ['a browser panel cookie', /CookieId/],
    ['a machine-local device name', /MonitoringDeviceName/],
  ])('contains no %s', (_label, pattern) => {
    expect(profileIni).not.toMatch(pattern)
  })

  it('contains no non-ASCII, which is how a locale-specific device name arrives', () => {
    // The first derivation wrote `MonitoringDeviceName=<a Korean default>` — correct on a Korean
    // Windows, meaningless on the church PC. Cheaper to ban the whole class than chase each string.
    const nonAscii = /[^\u0000-\u007F]/.exec(profileIni)
    expect(nonAscii?.[0] ?? null).toBeNull()
  })
})

describe('the profile sets only what is deliberate', () => {
  it('records Matroska, not mp4', () => {
    // Standing Rule 3: recording is always on whenever streaming is. An .mp4 whose OBS crashed
    // mid-write is unplayable — the recording of the service is simply gone. .mkv survives the same
    // crash and remuxes afterwards. This is the single most valuable line in the file.
    expect(profileIni).toMatch(/RecFormat2=mkv/)
  })

  it('pins 1920x1080 so the overlay page maps 1:1', () => {
    expect(profileIni).toMatch(/BaseCX=1920/)
    expect(profileIni).toMatch(/BaseCY=1080/)
    expect(profileIni).toMatch(/OutputCX=1920/)
    expect(profileIni).toMatch(/OutputCY=1080/)
  })

  it('leaves the encoder and the recording folder to OBS', () => {
    // Absent keys fall back to OBS's own defaults, computed on the machine that runs it. That is
    // exactly what a template wants, and it is why the allowlist is short.
    expect(profileIni).not.toMatch(/StreamEncoder=/)
    expect(profileIni).not.toMatch(/RecEncoder=/)
    expect(profileIni).not.toMatch(/FilePath=/)
  })
})

describe('user.ini selects the shipped profile and collection', () => {
  it('names the profile and collection the template actually provides', () => {
    expect(userIni).toMatch(/^Profile=Verger$/m)
    expect(userIni).toMatch(/^ProfileDir=Verger$/m)
    expect(userIni).toMatch(/^SceneCollection=Verger$/m)
    // The FILENAME, not just the display name — OBS loads by file, and a mismatch here means OBS
    // starts on an empty default collection with no error anywhere.
    expect(userIni).toMatch(/^SceneCollectionFile=Verger\.json$/m)
  })

  it('suppresses the auto-configuration wizard', () => {
    // Without FirstRun, OBS opens its wizard on the church PC, runs a bandwidth test in front of the
    // operator, and overwrites the profile this template just supplied.
    expect(userIni).toMatch(/^FirstRun=true$/m)
  })
})

describe('the scene collection is the one described in OBS-SETUP.md', () => {
  it('has exactly one scene, so there is no black scene to cut to by mistake', () => {
    expect(collection.scene_order).toEqual([{ name: 'Cam 1' }])
    expect(collection.current_program_scene).toBe('Cam 1')
  })

  it('names the overlay source exactly "Overlays"', () => {
    // The runbook and the setup guide both tell the operator to look for this name.
    expect(browserSource().name).toBe('Overlays')
  })

  it('points the browser source at the port Verger actually serves on', () => {
    // A drift guard with teeth: if overlay.port in portable/config.json is ever changed, the URL
    // baked into this template goes stale and the overlay silently never appears — OBS shows a
    // blank page and reports no error, and Verger reports 0 attached.
    const portableConfig = JSON.parse(
      readFileSync(join(REPO_ROOT, 'portable', 'config.json'), 'utf8'),
    ) as { overlay: { port: number } }

    expect(browserSource().settings?.['url']).toBe(
      `http://127.0.0.1:${String(portableConfig.overlay.port)}/overlay`,
    )
  })

  it.each([
    // Each of these is a checkbox in OBS whose wrong state looks identical to its right state until
    // it fails in front of the congregation.
    ['shutdown', false, 'destroys the page whenever the scene is not visible'],
    ['restart_when_active', false, 'reloads the page on every scene change'],
    ['reroute_audio', true, 'is the only reason video cues are audible in the mix'],
  ])('sets %s to %s, which otherwise %s', (key, expected) => {
    expect(browserSource().settings?.[key as string]).toBe(expected)
  })

  it('clears the CSS OBS pre-fills', () => {
    // OBS pre-populates a stylesheet that fights the overlay page's own layout.
    expect(browserSource().settings?.['css']).toBe('')
  })

  it('matches the canvas the profile declares', () => {
    expect(browserSource().settings?.['width']).toBe(1920)
    expect(browserSource().settings?.['height']).toBe(1080)
  })
})

describe('nothing secret ships in the template', () => {
  it('carries no obs-websocket config, because the password is generated per assembly', () => {
    // Standing Rule 5. A password committed here would be a shared secret in a public repo, and
    // obs-websocket listens on every interface — on a church wifi that is a stream anyone can take
    // over. `scripts/assemble-portable-obs.mts` generates a fresh one into the assembled folder.
    expect(JSON.stringify(collection)).not.toMatch(/server_password/)
    expect(profileIni).not.toMatch(/password/i)
  })
})
